USE BDLOGIST;
GO 

/*CREACIÓN DE TABLA VEHICULO*/

CREATE TABLE vehiculo
(COD_VEHICULO INT IDENTITY(400,1) NOT NULL,
TIPO_VEHICULO VARCHAR (20) NOT NULL,
PLACA VARCHAR (10) NOT NULL ,
CAPACIDAD NUMERIC (9) NOT NULL,
CONSTRAINT PK_VEHICULO PRIMARY KEY (COD_VEHICULO),
CONSTRAINT U_PLACA UNIQUE (PLACA))
GO

/*PRUEBA DE TABLA VEHICULO*/ 

INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('camion baranda','A0287F','12')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('camion','A0267F','10')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('Furgon','A1267F','12')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('camioneta','A0207F','5')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('camion volquete','A0217F','20')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('gruas','A0687F','12')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('camion baranda','A0787F','12')
GO
INSERT into vehiculo(TIPO_VEHICULO,PLACA, CAPACIDAD)
Values('camion baranda','A0277F','12')
GO

/*VISTA A TABLA VEHICULO*/ 

SELECT * FROM vehiculo
GO





/*CREACIÓN DE TABLA TRANSPORTISTA*/

CREATE TABLE transportista
(COD_CONDUCTOR INT IDENTITY(200,1) NOT NULL,
NOMBRE VARCHAR(100)NOT NULL,
APELLIDOS VARCHAR (100) NOT NULL,
DNI NUMERIC (8) NOT NULL,
TIPO_LICENCIA VARCHAR (1) NOT NULL,
FECHA_VENCIMIENTO_licencia VARCHAR (8),
LICENCIA_CONDUCIR VARCHAR (9) NOT NULL,
CONSTRAINT PK_CONDUCTOR PRIMARY KEY (COD_CODUCTOR),
CONSTRAINT U_DNI UNIQUE (DNI),
CONSTRAINT U_LICENCIA_CONDUCIR UNIQUE (LICENCIA_CONDUCIR),)
GO

/*PRUEBA DE TABLA TRANSPORTISTA*/ 

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('RODRIGO','RICSE BALDEÓN',75405879,'A','12/12/22','X08997130')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('MARIO','GONZALES VIVAR',75405878,'B','09/12/22','B08998130')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('ROCIO','RICSE MAYA',75405845,'C','11/01/22','C08997122')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('OSCAR','MOLINA MAGALLANES',75405877,'B','21/09/24','B08008130')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('BENJAMIN','CRISTINO CALDERON',75405822,'A','12/02/23','G08007130')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('LUIGUI','BARBOZA LOPEZ',75405855,'C','01/05/24','A08698130')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('CARMEN','CRISTINO CALDERON',75415822,'A','12/02/23','G08000130')
GO

INSERT into transportista (NOMBRE,APELLIDOS,DNI,TIPO_LICENCIA,FECHA_VENCIMIENTO_licencia,LICENCIA_CONDUCIR)
Values('JEAN CARLOS','COSTA MAMANI',75405005,'D','03/04/22','C08778130')
GO

/*VISTA A TABLA TRANSPORTISTA*/ 

SELECT * FROM transportista
GO







/*CREACIÓN DE TABLA CATEGORIA*/ 

CREATE TABLE CATEGORIA
(COD_CATEGORIA INT IDENTITY(700,1) NOT NULL,
NOMBRE_CATEGORIA VARCHAR(100)NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (COD_CATEGORIA)
)
GO

/*PRUEBA DE TABLA CATEGORIA*/ 

INSERT into categoria(NOMBRE_CATEGORIA)
Values('ALIMENTOS Y BEBIDAS')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('AUDIOVISUALES')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('BELLEZA')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('ARTESANÍA')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('OFICINA')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('CONSTRUCCIÓN')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('DEPORTES')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('EDUCACIÓN')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('ESTADO')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('HOGAR')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('MUSICA')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('ENTRETENIMIENTO')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('SALUD Y BIENESTAR')
GO

INSERT into categoria(NOMBRE_CATEGORIA)
Values('RESTAURANTES')
GO

/*VISTA A TABLA CATEGORIA*/ 

SELECT * FROM CATEGORIA
GO









/*CREACIÓN DE TABLA PRODUCTO*/ 

CREATE TABLE producto
(COD_PRODUCTO INT IDENTITY(100,1) NOT NULL,
NOMBRE_PRODUC VARCHAR(100)NOT NULL,
DESCRIPCIÓN VARCHAR (100) NOT NULL,
CANTIDAD NUMERIC (10) NOT NULL,
COD_CATEGORIA INT NOT NULL,
CONSTRAINT PK_PRODUCTO           PRIMARY KEY (COD_PRODUCTO),
CONSTRAINT FK_producto_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES categoria
)
GO

/*PRUEBA DE TABLA PRODUCTO*/ 

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Caminadora','400 W de potencia, color rojo',40,706)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Caja Panetón Gloría','1kg envasado en pallets',50,700)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Congeladora','2 compartimientos Lenovo',15,709)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Televisor LG','40 pulgadas',10,711)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Soda Field','six pack envasado en cajas de 24 unidades',56,700)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('PS4','Slim empacado en lotes de 20 unidades',20,711)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Ajinomen','Gallina en cajas de 40 unidades',40,700)
GO

INSERT into producto (NOMBRE_PRODUC,DESCRIPCIÓN,CANTIDAD,COD_CATEGORIA)
Values('Cama Paraiso','10 plazas empazado en lotes de 4 unidades',50,709)
GO

/*VISTA A TABLA PRODUCTO*/ 

SELECT * FROM producto
GO


DROP TABLE CLIENTE
GO

/*CREACIÓN DE TABLA CLIENTE*/ 

CREATE TABLE cliente
(COD_CLIENTE INT IDENTITY(1,1) NOT NULL,
RAZON_SOCIAL VARCHAR (100) NOT NULL,
RUC NUMERIC (11) NOT NULL,
TELEFONO NUMERIC (9) NOT NULL,
DIRECCIÓN VARCHAR (100) NOT NULL,
EMAIL nvarchar (50) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE),
CONSTRAINT U_RAZONSOCIAL UNIQUE (RAZON_SOCIAL),
CONSTRAINT U_TELEFONO UNIQUE (TELEFONO),
CONSTRAINT U_RUC UNIQUE (RUC),
CONSTRAINT U_EMAIL UNIQUE (EMAIL)
)
GO

/*PRUEBA DE TABLA CLIENTE*/ 

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('ALICORP',10565823441,978456111,'Calle ucayali 195','rgt2345_gr@gmail.com')
GO

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('COSTA',10456734561,978000345,'Jr. Ingenieros 445','costa_2334@gmail.com')
GO

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('CERROAZUL',1059999341,989122345,'Av La molina 234','cerrozaul@gmail.com')
GO

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('LG',10885678911,978090666,'Jr Las Flores 123','Lg_corporation@gmail.com')
GO

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('KFC',10533393241,978400221,'Av Javier Prado 434','KFC@gmail.com')
GO

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('PLAYSTATION',10500123211,998456001,'Jr Los Andes 234','playstation@gmail.com')
GO

INSERT into cliente (RAZON_SOCIAL,RUC,TELEFONO,DIRECCIÓN, EMAIL)
Values('BACKUS',10567773441,970456011,'Av Carretera Central 678','backus@gmail.com')
GO

/*VISTA A TABLA CLIENTE*/ 

SELECT * FROM cliente
GO








/*CREACIÓN DE TABLA ALMACEN*/ 

CREATE TABLE ALMACEN
(COD_ALMACEN INT IDENTITY(500,1) NOT NULL,
COD_PRODUCTO INT  NOT NULL,
NOMBRE_SECCION VARCHAR (3) NOT NULL,

CONSTRAINT PK_ALMACEN          PRIMARY KEY (COD_ALMACEN),
CONSTRAINT FK_ALMACEN_producto FOREIGN KEY (COD_PRODUCTO) REFERENCES producto)
GO

/*PRUEBA DE TABLA ALMACEN*/ 

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(101,'A01')
GO

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(105,'A12')
GO

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(104,'B18')
GO

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(107,'A23')
GO

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(102,'B28')
GO

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(106,'B18')
GO

INSERT into ALMACEN(COD_PRODUCTO,NOMBRE_SECCION)
Values(103,'A08')
GO

/*VISTA A TABLA ALMACEN*/ 

SELECT * FROM ALMACEN
GO






/*CREACIÓN DE TABLA SEDE*/

CREATE TABLE SEDE
(COD_SEDE INT IDENTITY(800,1) NOT NULL,
NOMBRE_SEDE VARCHAR (100) NOT NULL,
DIRECCION VARCHAR (100) NOT NULL,
CONSTRAINT U_NOMBRE_SEDE UNIQUE (NOMBRE_SEDE),
CONSTRAINT PK_SEDE PRIMARY KEY (COD_SEDE))
GO

/*PRUEBA DE TABLA CLIENTE*/ 

INSERT into SEDE (NOMBRE_SEDE,DIRECCION)
VALUES('SAN BORJA','Jr Cesar Vallejo 234')
GO

INSERT into SEDE (NOMBRE_SEDE,DIRECCION)
VALUES('ATE','Av. Atunez 452')
GO

INSERT into SEDE (NOMBRE_SEDE,DIRECCION)
VALUES('SURQUILLO','Jr. Los Olimpos 234')
GO

INSERT into SEDE (NOMBRE_SEDE,DIRECCION)
VALUES('VICTORIA','Av. El belisario')
GO

/*VISTA A TABLA SEDE*/ 

SELECT * FROM SEDE
GO


/*CREACIÓN DE TABLA SERVICIO*/ 

CREATE TABLE SERVICIO
(COD_TSERV INT IDENTITY(2200,1) NOT NULL,
TIPO_SERV VARCHAR (100) NOT NULL,
CONSTRAINT U_TSERV UNIQUE (TIPO_SERV),
CONSTRAINT PK_TSERVICIO PRIMARY KEY (COD_TSERV))
GO

/*PRUEBA DE TABLA SERVICIO*/

INSERT into SERVICIO (TIPO_SERV)
VALUES('CADENA DE FRIO')
GO

INSERT into SERVICIO (TIPO_SERV)
VALUES('FREIGHT FORWARDING')
GO

INSERT into SERVICIO (TIPO_SERV)
VALUES('ALMACEN')
GO

INSERT into SERVICIO (TIPO_SERV)
VALUES('TRANSPORTE')
GO

/*VISTA A TABLA SERVICIO*/ 

SELECT * FROM SERVICIO
GO


/*CREACIÓN DE TABLA REGISTRO*/ 

CREATE TABLE REGISTRO
(COD_SERV INT IDENTITY(300,1) NOT NULL,
COD_TSERV INT  NOT NULL,
T_SERV VARCHAR (100) NOT NULL,
CANTIDAD numeric (38)NOT NULL,
COD_VEHICULO INT NOT NULL,
COD_CONSANDUCTOR INT  NOT NULL,
COD_PRODUCTO INT NOT NULL,
COD_CLIENTE INT NOT NULL,
COD_SEDE INT NOT NULL,

CONSTRAINT PK_SERVICIO  PRIMARY KEY (COD_SERV),

------DATOS DEL VEHICULO------
CONSTRAINT FK_REGISTRO_vehiculo FOREIGN KEY(COD_VEHICULO) REFERENCES vehiculo,

------DATOS DEL CONDUCTOR------
CONSTRAINT FK_REGISTRO_transportista  FOREIGN KEY(COD_CODUCTOR) REFERENCES transportista,

------DATOS DEL PRODUCTO------
CONSTRAINT FK_REGISTRO_producto FOREIGN KEY(COD_PRODUCTO) REFERENCES producto,

------DATOS DEL cliente------
CONSTRAINT FK_REGISTRO_cliente FOREIGN KEY(COD_CLIENTE) REFERENCES cliente,

------DATOS DEL SEDE------
CONSTRAINT FK_REGISTRO_SEDE FOREIGN KEY(COD_SEDE) REFERENCES SEDE,

------DATOS DEL TIPO DE SRVICIO------
CONSTRAINT FK_REGISTRO_SERVICIO FOREIGN KEY(COD_TSERV) REFERENCES SERVICIO,
)
GO

/*PRUEBA DE TABLA REGISTRO*/

INSERT into REGISTRO(COD_TSERV,T_SERV,CANTIDAD,COD_VEHICULO,COD_CODUCTOR,COD_PRODUCTO,COD_CLIENTE,COD_SEDE)
VALUES(2202,'HOLA',12,400,201,101,4,802)
GO


UPDATE REGISTRO
SET T_SERV = (select TIPO_SERV from servicio where SERVICIO.COD_TSERV = REGISTRO.COD_TSERV)
go

/*VISTA DE TABLA REGISTRO*/

SELECT * FROM REGISTRO
GO